[tool.poetry]
name = "arxiv-bot"
version = "0.1.0"
description = ""
authors = ["Ryosuke Yamaguchi"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.58.1"
py-cord = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
